import { TopLevelSection } from '../context/CloudFormationEnums';

export const templateSectionDocsMap: ReadonlyMap<TopLevelSection, string> = new Map<TopLevelSection, string>([
    [
        TopLevelSection.Resources,
        [
            '**Resources**',
            '\n',
            '---',
            'The `Resources` section is a required top-level section in a CloudFormation template.',
            'It declares the AWS resources that you want CloudFormation to provision and configure as part of your stack.',
            '\n',
            '[Source Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html)',
        ].join('\n'),
    ],
    [
        TopLevelSection.Parameters,
        [
            '**Parameters**',
            '\n',
            '---',
            'Use the optional Parameters section to customize your templates. With parameters, you can input custom values to your template each time you create or update a stack. By using parameters in your templates, you can build reusable and flexible templates that can be tailored to specific scenarios.',
            '\n',
            'By defining parameters of the appropriate type, you can choose from a list of identifiers of existing resources when you use the console to create your stack. For more information, see [Specify existing resources at runtime with CloudFormation-supplied parameter types.](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-supplied-parameter-types.html)',
            '\n',
            'Parameters are a popular way to specify property values of stack resources. However, there may be settings that are region dependent or are somewhat complex for users to figure out because of other conditions or dependencies. In these cases, you might want to put some logic in the template itself so that users can specify simpler values (or none at all) to get the results that they want, such as by using a mapping. For more information, see [CloudFormation template Mappings syntax.](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html)',
            '\n',
            '[Source Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html)',
        ].join('\n'),
    ],
    [
        TopLevelSection.Outputs,
        [
            '**Outputs**',
            '\n',
            '---',
            'The optional Outputs section declares output values for the stack. These output values can be used in various ways:',
            '- **Capture important details about your resources** – An output is a convenient way to capture important information about your resources. For example, you can output the S3 bucket name for a stack to make the bucket easier to find. You can view output values in the **Outputs** tab of the CloudFormation console or by using the [describe-stacks](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/service_code_examples.html#describe-stacks-sdk) CLI command.',
            '- **Cross-stack references** – You can import output values into other stacks to [create references between stacks](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-exports.html). This is helpful when you need to share resources or configurations across multiple stacks.',
            '\n',
            '**Important**',
            '\n',
            "CloudFormation doesn't redact or obfuscate any information you include in the Outputs section. We strongly recommend you don't use this section to output sensitive information, such as passwords or secrets.",
            '\n',
            "Output values are available after the stack operation is complete. Stack output values aren't available when a stack status is in any of the IN_PROGRESS statuses. We don't recommend establishing dependencies between a service runtime and the stack output value because output values might not be available at all times.",
            '\n',
            '[Source Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html)',
        ].join('\n'),
    ],
    [
        TopLevelSection.Mappings,
        [
            '**Mappings**',
            '\n',
            '---',
            'The optional `Mappings` section helps you create key-value pairs that can be used to specify values based on certain conditions or dependencies.',
            '\n',
            'One common use case for the `Mappings` section is to set values based on the AWS Region where the stack is deployed. This can be achieved by using the `AWS::Region` pseudo parameter. The `AWS::Region` pseudo parameter is a value that CloudFormation resolves to the region where the stack is created. Pseudo parameters are resolved by CloudFormation when you create the stack.',
            '\n',
            'To retrieve values in a map, you can use the `Fn::FindInMap` intrinsic function within the Resources section of your template.',
            '\n',
            '[Source Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html)',
        ].join('\n'),
    ],
    [
        TopLevelSection.Metadata,
        [
            '**Metadata**',
            '\n',
            '---',
            '`Metadata` stores additional information using JSON or YAML objects. The types of template-level metadata you can use in your template include:',
            '\n',
            '**Custom metadata**',
            '\n',
            "Stores user-defined key-value pairs. For example, you can provide additional information that doesn't impact resource creation but offers additional context about the infrastructure, team, or deployment specifics.",
            '\n',
            '**AWS::CloudFormation::Interface**',
            '\n',
            "Defines the grouping and ordering of input parameters when they're displayed in the CloudFormation console. By default, the CloudFormation console alphabetically sorts parameters by their logical ID.",
            '\n',
            '**AWS::CloudFormation::Designer**',
            '\n',
            'AWS CloudFormation Designer (Designer) reached end of life on February 5, 2025.',
            '\n',
            '**Important**',
            'During a stack update, you cannot update the Metadata section by itself. You can update it only when you include changes that add, modify, or delete resources.',
            '\n',
            'CloudFormation does not transform, modify, or redact any information you include in the Metadata section. Because of this, we strongly recommend you do not use this section to store sensitive information, such as passwords or secrets.',
            '\n',
            '[Source Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/metadata-section-structure.html)',
        ].join('\n'),
    ],
    [
        TopLevelSection.Rules,
        [
            '**Rules**',
            '\n',
            '---',
            'The `Rules` section is an optional part of a CloudFormation template that enables custom validation logic. When included, this section contains rule functions that validate parameter values before CloudFormation creates or updates any resources.',
            '\n',
            'Rules are useful when standard parameter constraints are insufficient. For example, if SSL is enabled, both a certificate and domain name must be provided.',
            '\n',
            '[Source Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/rules-section-structure.html)',
        ].join('\n'),
    ],
    [
        TopLevelSection.Conditions,
        [
            '**Conditions**',
            '\n',
            '---',
            'The optional `Conditions` section contains statements that define the circumstances under which entities are created or configured. For example, you can create a condition and then associate it with a resource or output so that CloudFormation only creates the resource or output if the condition is true. Similarly, you can associate the condition with a property so that CloudFormation only sets the property to a specific value if the condition is true. If the condition is false, CloudFormation sets the property to a different value that you specify.',
            '\n',
            "You might use conditions when you want to reuse a template that can create resources in different contexts, such as a test environment versus a production environment. In your template, you can add an `EnvironmentType` input parameter, which accepts either `prod` or `test` as inputs. For the production environment, you might include Amazon EC2 instances with certain capabilities; however, for the test environment, you want to use reduced capabilities to save money. With conditions, you can define which resources are created and how they're configured for each environment type.",
            '\n',
            'Conditions are evaluated based on predefined pseudo parameters or input parameter values that you specify when you create or update a stack. Within each condition, you can reference another condition, a parameter value, or a mapping. After you define all your conditions, you can associate them with resources and resource properties in the `Resources` and `Outputs` sections of a template.',
            '\n',
            'At stack creation or stack update, AWS CloudFormation evaluates all the conditions in your template before creating any resources. Resources that are associated with a true condition are created. Resources that are associated with a false condition are ignored. CloudFormation also re-evaluates these conditions at each stack update before updating any resources. Resources that are still associated with a true condition are updated. Resources that are now associated with a false condition are deleted.',
            '\n',
            '**Important**',
            '\n',
            "During a stack update, you can't update conditions by themselves. You can update conditions only when you include changes that add, modify, or delete resources.",
            '\n',
            '**How to use conditions**',
            '\n',
            'Depending on the entity you want to conditionally create or configure, you must include statements in the following template sections:',
            '**Parameters section**',
            "Define the inputs that you want your conditions to evaluate. The conditions evaluate to true or false based on the values of these input parameters. If you want your conditions to evaluate pseudo parameters, you don't need to define the pseudo parameters in this section; pseudo parameters are predefined by CloudFormation. For more information about pseudo parameters, see .",
            '\n',
            '**Conditions section**',
            '\n',
            'Define conditions by using the intrinsic condition functions. These conditions determine when CloudFormation creates the associated resources. For examples, see Sample templates.',
            '\n',
            '**Resources and Outputs sections**',
            '\n',
            "Associate conditions with the resources or outputs that you want to conditionally create. CloudFormation creates entities that are associated with a true condition and ignores entities that are associated with a false condition. Use the Condition key and a condition's logical ID to associate it with a resource or output. To conditionally specify a property, use the Fn::If function. For an example, see Associating a condition.",
            '\n',
            '[Source Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html)',
        ].join('\n'),
    ],
    [
        TopLevelSection.Transform,
        [
            '**Transform**',
            '\n',
            '---',
            'The optional `Transform` section specifies one or more macros that CloudFormation uses to process your template in some way.',
            '\n',
            "Macros can perform simple tasks like finding and replacing text, or they can make more extensive transformations to the entire template. CloudFormation executes macros in the order that they're specified. When you create a change set, CloudFormation generates a change set that includes the processed template content. You can then review the changes and execute the change set. For more information about how macros work, see [Perform custom processing on CloudFormation templates with template macros](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-macros.html).",
            '\n',
            '[Source Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html)',
        ].join('\n'),
    ],
    [
        TopLevelSection.AWSTemplateFormatVersion,
        [
            '**AWSTemplateFormatVersion**',
            '\n',
            '---',
            'The `AWSTemplateFormatVersion` section (optional) identifies the template format version that the template conforms to. The latest template format version is `2010-09-09` and is currently the only valid value.',
            '\n',
            "The template format version isn't the same as the API version. The template format version can change independently of the API versions.",
            '\n',
            "The value for the template format version declaration must be a literal string. You can't use a parameter or function to specify the template format version. If you don't specify a value, CloudFormation assumes the latest template format version. The following snippet is an example of a valid template format version declaration:",
            '\n',
            '**JSON**',
            '\n',
            '```json',
            '"AWSTemplateFormatVersion" : "2010-09-09"',
            '```',
            '\n',
            '**YAML**',
            '\n',
            '```yaml',
            'AWSTemplateFormatVersion: 2010-09-09',
            '```',
            '[Source Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html)',
        ].join('\n'),
    ],
    [
        TopLevelSection.Description,
        [
            '**Description**',
            '\n',
            '---',
            'The `Description` section (optional) enables you to include a text string that describes the template. This section must always follow the template format version section.',
            '\n',
            'The value for the description declaration must be a literal string that is between 0 and 1024 bytes in length. You cannot use a parameter or function to specify the description. The following snippet is an example of a description declaration:',
            '**Important**',
            'During a stack update, you cannot update the Description section by itself. You can update it only when you include changes that add, modify, or delete resources.',
            '\n',
            '**JSON**',
            '\n',
            '```js',
            '"Description" : "Here are some details about the template."',
            '```',
            '\n',
            '**YAML**',
            '\n',
            '```',
            'Description: Here are some details about the template.',
            '```',
            '[Source Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-description-structure.html)',
        ].join('\n'),
    ],
    // TODO: Update with official AWS documentation when available
    [
        TopLevelSection.Constants,
        [
            '**Constants**',
            '\n',
            '---',
            'The optional `Constants` section allows you to define reusable values that can be referenced throughout your template. Constants can be strings or objects and are referenced directly by their name in intrinsic functions like `Ref` and `Sub`.',
            '\n',
            'Constants are useful for defining values that are used multiple times in your template, making your templates more maintainable and reducing duplication.',
            '\n',
            '**Note:** This feature requires the `AWS::LanguageExtensions` transform.',
            '\n',
            '[Source Documentation](https://docs.aws.amazon.com/)',
        ].join('\n'),
    ],
]);
